[package]
name = "trellis"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
  "crates/trellis-primitives",
  "crates/trellis-terminal",
  "crates/trellis-ui",
]

[dependencies]
trellis-terminal = { path = "crates/trellis-terminal" }
trellis-ui = { path = "crates/trellis-ui" }
