[package]
name = "trellis"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
  "crates/trellis_core",
  "crates/trellis_graphics",
  "crates/trellis_terminal",
]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
trellis_terminal = { path = "crates/trellis_terminal" }
trellis_graphics = { path = "crates/trellis_graphics" }
trellis_core = { path = "crates/trellis_core" }
